src/compoents/RichTextEditor.jsx
src/compoents/mentorship/FormMentorCareer.jsx
src/compoents/mentorship/FormMentorshipValues.jsx
src/pages/NewMentorPage.jsx

This PR refactors some of the mentor pages to reduce code duplication, increase code quality, as well as optimizing or adding a number of helper functions.  This is the first of several PRs related to refactoring the Mentor pages.
Unfortunately, I don't have access to the API backend currently - please ensure no API functionality is broken during review.
ping @DeltaV93

Mentor Pages Refactor 1

---

src/pages/AllJobsPage.jsx

I added a check to see if the user has community-posted jobs; if they do, we show the post. If they don't we show the box to push people box that asks people to post a job to the job board.

tbc-104 hide "jobs you posted" box if user did not post any jobs

---

.github/PULL_REQUEST_TEMPLATE /pull_request_template.md

Created a pull request template to create a standard for how we create a pull request. This template includes the following:
- Description: A summary of the changes being proposed.
- Related Issue(s): Links to related issues in the repository.
- Motivation and Context: The reason for the changes and their context.
- Testing: Information on how the changes have been tested.
- Screenshots: If applicable, to visually demonstrate the changes.
- Types of Changes: To categorize the nature of the changes.
- Checklist: A list of tasks to ensure the PR adheres to project guidelines

Created a pull_request_template.md

---

src/providers/AuthProvider.jsx

Updated the UI to work with logout

tbc-106 updated the ui to support logout

---

.npmrc
example.env
package-lock.json
package.json
src/App.jsx

Added the private npm package to the repo or ticket tbc-127

Install tbc-components

---

README.md

Updating the readme to include details needed for the project

tbc-100 First go at new README.md

---

src/App.jsx

Added questions page for reviews from stash to complete the prod build

tbc-144 Added questions page for reviews

---

.gitignore
biome.json
package.json
prettier.config.js
scripts/local-dev-setup.mjs

This PR adds a script for an automated configuration process when working on the project locally.
To run the script:
```sh
node scripts/local-dev-setup.mjs
```
You will be prompted for the TBC development API server URL, which can be provided by a TBC staff/team member.
This PR also moves the `src/example.env` to `./example.env`.
ping @DeltaV93

Add Local Dev Setup Script

---

src/App.jsx
src/compoents/WrapperReview.jsx
src/pages/dashboards/MemberDashboardPage.jsx

Updated the membership page only to show review access to users who have access to this feature.
Linear Issue [#TBC-151]
-   [x] New feature (non-breaking change which adds functionality)
-   [x] I have read the CONTRIBUTING document.
-   [x] My code follows the code style of this project.
-   [x] I have performed a self-review of my own code.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I have made corresponding changes to the documentation.
-   [x] My changes generate no new warnings.
-   [ ] I have added tests that prove my fix is effective or that my …

TBC-151 added logic to hide/show review access

---

src/App.jsx
src/compoents/FeatuerCards.jsx
src/index.css
src/pages/Dashboard.jsx
src/pages/dashboards/MemberDashboardPage.jsx
src/temp-theme.js

Adding styling to TBC members landing page to create a styled version of the feature cards. This update includes the setup with a temporary theme to the app to support styling until the tbc component library is ready, and the creation of the FeatuerCard. 
Linear Issue [#TBC-159](https://linear.app/techbychoiceorg/issue/TBC-159/add-default-app-styling)
Linear Issue [#TBC-160](https://linear.app/techbychoiceorg/issue/TBC-160/style-feature-cards-for-member-landing-page)
-   [x] Styling Updates (non-breaking change which updates an UX/Visuals)
-   [ ] Documentation …

Tbc 159 tbc-160

---

src/App.jsx
src/index.css
src/pages/dashboards/MemberDashboardPage.jsx

Styled the community announcements and added a new icon to the card. Made sure the card worked on mobile view.
Linear Issue [#TBC-161](https://linear.app/techbychoiceorg/issue/TBC-161/style-announcements)
-   [x] I have read the CONTRIBUTING document.
-   [x] My code follows the code style of this project.
-   [x] I have performed a self-review of my own code.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I have made …

Tbc 161 Styled Community Announcements

---

src/pages/AllMembersPage.jsx
src/pages/ViewMemberProfile.jsx
src/temp-theme.js

- Added font styles to this page
- Clean up UI on the member profile page
- Moved all members page from cards to table
Linear Issue [#TBC-166](https://linear.app/techbychoiceorg/issue/TBC-166/ui-updates-for-putting-members-into-tables)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] I have commented my code, particularly in …

Tbc 166 Updated view all memebers paage

---

src/compoents/layout/NavBar.jsx

Added the correct links based on auth status for mobile 
Added missing dashboard links
Linear Issue [#TBC-159]
-   [ ] I have made corresponding changes to the documentation.
-   [ ] My changes generate no new …

tbc-159 Added missing styles to navbar 

---

src/App.jsx

Added a11y fix to work with navbar updates

---

src/pages/CreateAccountPage.jsx
src/pages/LoginPage.jsx

tbc-159 Updated styling on login & create account page

---

src/compoents/FeatuerCards.jsx
src/pages/dashboards/MemberDashboardPage.jsx

tbc-159 updated feature card & made bottom cards aligned

---

src/pages/AllJobsPage.jsx
src/pages/ViewJobPage.jsx

tbc-159 Cleaned up the UI for the job pages

---

src/pages/ViewMemberProfile.jsx

tbc-159 code cleanup and ui updates for member profile

---

src/App.jsx
src/compoents/WrapperReview.jsx
src/compoents/layout/NavBar.jsx
src/pages/AllJobsPage.jsx
src/pages/CreateAccountPage.jsx
src/pages/MemberSignupPage.jsx
src/pages/NewMemeberPage.jsx
src/providers/PrivateRouteProvider.jsx

- Pushing people to complete their profile before hitting the app & fixed an infinite loop issue coming from MUI element being passed an obj when it needs an array 
- Added missing navbar items + code cleanup
Linear Issue [#TBC-159](url)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] I have commented my code, particularly in …

tbc-159 Pushing people to onboarding workflow during 

---

src/compoents/onboarding/CompanyProfileStep.jsx
src/lib/routes.ts
src/pages/CheckEmailPage.jsx
src/pages/CompanySignupPage.jsx
src/pages/NewCompanyPage.jsx
src/pages/onboarding/company/ConfirmAccountPage.jsx
src/pages/onboarding/company/ConfirmAgreementPage.jsx
src/providers/AuthProvider.jsx
src/providers/PrivateRouteProvider.jsx
src/providers/WorkflowProvider.jsx

- Added blockers to block users from hitting different workflows based on current status 
- Made updates to support BE changes 
Linear Issue [#TBC-159](url) …

Tbc 159 Company onboarding workflows

---

src/App.jsx
src/compoents/layout/NavBarReviews.jsx
src/compoents/layout/NavBarWrapper.jsx
src/lib/routes.ts
src/pages/AllCompaniesPage.jsx
src/pages/AllJobsPage.jsx
src/pages/CreateReviewAccountPage.jsx
src/pages/Dashboard.jsx
src/pages/JobReferralPage.jsx
src/pages/NewCompanyPage.jsx
src/pages/NewMemeberPage.jsx
src/pages/NewMentorPage.jsx
src/pages/TermsAndAgreementsWrapperPage.jsx
src/pages/ViewCompanyPage.jsx
src/pages/dashboards/ReviewsDashboardPage.jsx
src/pages/onboarding/ConfirmOpenDoorsAgreementPage.jsx
src/pages/onboarding/company/ConfirmAccountPage.jsx
src/providers/PrivateRouteProvider.jsx

Updated the UI flow to support the onbording flow of new review user type by making the company onboarding flow more dynamic. 
Updated how the navbar works to support dynamic navbar based on user type
Added a searchable view all companies page & created a new review account dashboard
Linear Issue [#TBC-176](https://linear.app/techbychoiceorg/issue/TBC-176/create-the-ui)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] My code follows …

Tbc 176 Create Review Account Onboarding and Supported UI

---

.gitignore
src/pages/ViewJobPage.jsx

Hiding "Interview process when the job doesn't have those details provided
Fixes # (tbc-209)
Linear Issue [#tbc-209](https://linear.app/techbychoiceorg/issue/TBC-209/job-page-shows-interview-process-even-if-the-field-is-blank) …

[tbc-209] Hide interview process on job page if not provided
